apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gatewayapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gatewayapi
    spec:
      containers:
      - name: gatewayapi
        image: alexandreceti/gatewayapi
        ports:
        - containerPort: 8080

