apiVersion: v1
kind: Service
metadata:
  name: identity
  labels:
    app: identity
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    app: identity
status:
  loadBalancer: {}
